version: '3.3'
services:
    event-sink:
        container_name: event-sink
        environment:
            - QUARKUS_LOG_LEVEL=TRACE
            - QUARKUS_HTTP_PORT=8080
            - RABBITMQ_HOST=ares
            - RABBITMQ_PORT=5672
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - "MP_JWT_VERIFY_PUBLICKEY=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5xplFDcgZc6YYnuzgWbwoJjH1MHcNo6aqbWTbCmFVuHG5Y3tOWQ16W3mi7A+vqVH4Dr8DUPMcN1dpFAdebzSoNM1CpIYEa1JnCyeaJDkilXN1H9WsTiaXYM+a32qJfDk4GPHACVbZjkp6uo761OUTY6HOsDnNE59DHeNTK80WM6I8Rv3qZe0OA2zrD6tuQdmNsl+pUtOEM/g526c7pgWv8dLEkdXA+6qlnROK4wz+Sm2xEovOKNVjhSiBCuUAzGORuF4V5AfFDIvjEFo57z961ASic6Yc5XjRiH/92rT1goVk5HEB8ix2pm91PHMW1nr9rJHFADbBDiJqiaree6eGQIDAQAB-----END PUBLIC KEY-----"
        ports:
            - '8077:8080'
        image: 'nherbaut/event-sink:1.0.0-SNAPSHOT'
    rabbitmq:
            hostname: ares
            ports:
                - '15672:15672'
                - '15671:15671'
                - '5672:5672'
            container_name: some-rabbit
            image: 'rabbitmq:management'
